<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWKs77DP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWKs77DP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWKs77DP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWKs77DP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWKs77DP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WKs77DP',
    'container.build_id' => '6ac08223',
    'container.build_time' => 1572005729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWKs77DP');
