<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIHf6Yjx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIHf6Yjx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIHf6Yjx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIHf6Yjx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIHf6Yjx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IHf6Yjx',
    'container.build_id' => 'c298c9e5',
    'container.build_time' => 1571995240,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIHf6Yjx');
